// <auto-generated />
namespace DotnetFramework48Lab01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addImpge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addImpge));
        
        string IMigrationMetadata.Id
        {
            get { return "202503081031284_addImpge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
