// <auto-generated />
namespace DotnetFramework48Lab01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addsuperherotable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsuperherotable));
        
        string IMigrationMetadata.Id
        {
            get { return "202502211624563_addsuperherotable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
